#!/usr/bin/env python3
"""
sync_manifest_to_ts.py — Standalone manifest sync tool
Converts sadik_v3/sadik-firmware/data/clips/clips-manifest.json
         -> sadik-app/src/assets/colorClipManifest.ts

Usage:
  python scripts/sync_manifest_to_ts.py
  python scripts/sync_manifest_to_ts.py --manifest <path> --out <path>

Run after encode_all.py completes, or separately to re-sync without re-encoding.
"""

import argparse
import json
from pathlib import Path

SCRIPT_DIR    = Path(__file__).parent
FIRMWARE_DIR  = SCRIPT_DIR.parent           # sadik_v3/sadik-firmware/
SADIK_V3_ROOT = FIRMWARE_DIR.parent         # sadik_v3/
REPO_ROOT     = SADIK_V3_ROOT.parent        # repo root

DEFAULT_MANIFEST = FIRMWARE_DIR / "data" / "clips" / "clips-manifest.json"
DEFAULT_TS_OUT   = REPO_ROOT / "sadik-app" / "src" / "assets" / "colorClipManifest.ts"

DEFAULT_FPS = 24


def write_ts(manifest_data: dict, ts_path: Path) -> None:
    clips     = manifest_data.get("clips", [])
    generated = manifest_data.get("generated", "unknown")
    target    = manifest_data.get("target", {})
    fps       = target.get("fps", DEFAULT_FPS) or DEFAULT_FPS

    lines = []
    lines.append("/**")
    lines.append(" * Color clip duration map — auto-generated by sync_manifest_to_ts.py")
    lines.append(f" * Generated: {generated}")
    lines.append(f" * Source: sadik_v3/sadik-firmware/data/clips/*.mjpeg @ {fps}fps")
    lines.append(" *")
    lines.append(" * Usage: import { COLOR_CLIP_DURATION_MS, COLOR_CLIP_FALLBACK_MS } from './colorClipManifest';")
    lines.append(" *        const gap = COLOR_CLIP_DURATION_MS[clipName] ?? COLOR_CLIP_FALLBACK_MS;")
    lines.append(" */")
    lines.append("")
    lines.append("/** Fallback gap (ms) when clip name is not in the map. */")
    lines.append("export const COLOR_CLIP_FALLBACK_MS = 1500;")
    lines.append("")
    lines.append("/**")
    lines.append(" * LittleFS clip name -> duration in milliseconds.")
    lines.append(f" * Derived from actual frame count parsed from each .mjpeg at {fps} fps.")
    lines.append(" */")
    lines.append("export const COLOR_CLIP_DURATION_MS: Record<string, number> = {")

    max_len = max((len(c["name"]) for c in clips), default=10)

    for clip in clips:
        name   = clip["name"]
        frames = clip.get("frames", 0)
        clip_fps = clip.get("fps", fps) or fps
        dur_ms = round(frames / clip_fps * 1000) if frames else 0
        pad    = " " * (max_len - len(name) + 1)
        lines.append(f"  {name}{pad}: {dur_ms},")

    lines.append("};")
    lines.append("")

    ts_path.parent.mkdir(parents=True, exist_ok=True)
    ts_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[sync] colorClipManifest.ts written -> {ts_path}")


def main():
    parser = argparse.ArgumentParser(description="Sync clips-manifest.json to colorClipManifest.ts")
    parser.add_argument(
        "--manifest", default=str(DEFAULT_MANIFEST),
        help=f"Path to clips-manifest.json. Default: {DEFAULT_MANIFEST}"
    )
    parser.add_argument(
        "--out", default=str(DEFAULT_TS_OUT),
        help=f"Path to output colorClipManifest.ts. Default: {DEFAULT_TS_OUT}"
    )
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    ts_path       = Path(args.out)

    if not manifest_path.exists():
        print(f"[sync] ERROR: manifest not found: {manifest_path}")
        print("  Run encode_all.py first to generate clips-manifest.json")
        raise SystemExit(1)

    manifest_data = json.loads(manifest_path.read_text(encoding="utf-8"))
    clips = manifest_data.get("clips", [])
    print(f"[sync] Loaded manifest: {len(clips)} clips from {manifest_path}")

    write_ts(manifest_data, ts_path)


if __name__ == "__main__":
    main()
